console.log('saif'=='saif')
console.log('saif'=='Saif')
console.log('saif'=='Saif'.toLowerCase())
console.log('saif'!='Saif'.toLowerCase())
console.log(1==1)
console.log(1!=1)
console.log(1<1)
console.log(1>1)
console.log(1<=1)
console.log(1>=1)
console.log(1==1 && 1<=1 || 1<1)
var list=['a','b']
console.log(Array.isArray(list))
console.log(!Array.isArray(list))
