var location = ['Margala', 'Himalya', 'Khyber', 'Hunza', 'Kalash']
console.log(location)
console.log([...location].sort())
console.log(location)
console.log([...location].sort().reverse())
console.log(location)
location.reverse()
console.log(location)
location.reverse()
console.log(location)
location.sort(location)
console.log(location)
location.reverse()
console.log(location)
